name: cubit_counter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 6.0.3
  equatable: 1.2.5
  flutter_bloc: 6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 1.0.2

flutter:
  uses-material-design: true
